---
title: "Reproducible Workflows: Github and Docker Task 3"
html:
    code-tools: true
    highlight-style: github
    embed-resources: true
---

1.	Clone the repository https://github.com/zuphilip/analyze-mega-journals to your computer locally.
2.	Install Docker on your computer such that you can use it with a terminal (NOT the Docker Desktop):
    * For Ubuntu: https://docs.docker.com/engine/install/ubuntu/
    * For macOS: https://dev.to/mochafreddo/running-docker-on-macos-without-docker-desktop-64o
    * For Windows we recommend to use the Windows Subsystem Linux (WSL) with Ubuntu: https://learn.microsoft.com/en-uswindows/wsl/install (NOT the Docker Desktop . Then you can also follow the steps in a).
3.	Open a terminal and navigate to the folder where you have copied the files from Step 1.
4.	Run the following command:
``` bash
docker run -ti --rm -p 8888:8888 -v "${PWD}":/home/jovyan/work quay.io/jupyter/datascience-notebook
```
5.	Open the shown URL in your browser (maybe replace 127.0.0.1 with localhost).
6.	Open the JupyterNotebook analyze.ipynb.
7.	Run the first computations to regenerate the first three figures (stop at Refetch and update the data (optional))
8.	Have any changes to files occured? And if so, which files have changed and what about them has changed?
9.	Stop the process in the terminal, where docker is running, by pressing Ctrl + C (⌘ + . for macOS).
